domain: shortclick.duckdns.org
shortener:
  image_tag: "008687fdb9c1f130f3fad4155e19424a40e9a900"
  db:
    user: shortener_service
    name: shortener_db
certbot_email: yaroslav.varichenko@gmail.com
